# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build e Deploy - eAgenda MVC

on: # Gatilho do fluxo de trabalho
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build: # Compila o projeto e o publica em uma pasta raíz
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4 # Puxa os arquivos do repositório

      - name: Set up .NET Core # Instala o .NET 8 na máquina executando o workflow
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
  
  test:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4 # Puxa os arquivos do repositório

      - name: "Set up Chrome"
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
  
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Run tests
        run: dotnet test --configuration Release --verbosity normal
        env:
          CI: true
          ASPNET_ENVIRONMENT: "Testing"

  migrate:
    runs-on: windows-latest
    needs: [build, test]
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: Install EF Core CLI
      run: dotnet tool install --global dotnet-ef --version 8.*
      
    - name: Apply EF Core migrations
      run: dotnet ef database update --project ./eAgenda.Infraestrutura.Orm --startup-project ./eAgenda.WebApp
      env:
        SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}

  deploy:
    runs-on: windows-latest
    needs: [build, test, migrate]
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0818A7A7B58A4B7D80901C78DF0CD658 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7B621A0E3C484CB3A1FF6E8ECD43DADD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C56680E7AF914921837F906FA9E99727 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eAgenda-marlon'
          slot-name: 'Production'
          package: .

          
